//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.07 at 10:59:54 AM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bnr.ro/xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ro.cobinance.money.bnr.xml;
